Aiven-Open/pghoard

- README.rst
- pghoard/basebackup.py
- pghoard/compressor.py
- pghoard/pghoard.py
- pghoard/restore.py
- test/test_basebackup.py
- test/test_restore.py
Add support for recovery_target_time and recovery_target_xid
> Recovery target

- pghoard/basebackup.py
- pghoard/common.py
- pghoard/compressor.py
- pghoard/object_storage/azure.py
- pghoard/object_storage/google.py
- pghoard/object_storage/s3.py
- pghoard/pghoard.py
- pghoard/restore.py
- pghoard/webserver.py
- test/test_pghoard.py
Ensure we always have up-to-date local metadata including the compression information. We'll need this later for encrypted data. A round of random fixes preparing for the eventual stacked transformations in addition to just compression.
> Local basebackup via compress flow

- pghoard/compressor.py
- pghoard/object_storage/__init__.py
- pghoard/object_storage/google.py
- pghoard/object_storage/s3.py
- pghoard/pghoard.py
- pghoard/restore.py
- pghoard/webserver.py
- test/test_compressor.py
* Store metadata for WAL files too
* Perform decompression if and only if compression_algorithm is set in metadata
The same fixture will be used for backup encryption.
> Decompress on metadata

- pghoard/restore.py
Add --recovery-target-action argument for passing the same setting to Postgres recovery.conf. Valid values are 'pause' (default), 'promote' and 'shutdown'. See Postgres documentation for the resulting behaviour.
> restore: support specifying recovery-target-action via arguments

- pghoard/restore.py
- test/test_restore.py
Also added test cases for verifying that we get zero or one of
`recovery_target_name`, `recovery_target_time` and `recovery_target_xid`.
Also return nicer error messages about invalid timestamps for
`recovery_target_time` and stop requiring (unused) `filename` and
`target_path` arguments for get-basebackup-http.
> restore: allow recovery_end_command and recovery_target_name

- pghoard/archive_sync.py
- pghoard/common.py
- pghoard/object_storage/__init__.py
- pghoard/restore.py
- pghoard/webserver.py
- test/conftest.py
- test/test_basebackup.py
- test/test_common.py
- test/test_webserver.py
* Synchronize .history files
* Synchronize all WAL files since last basebackup
> Archive sync improvements

- pghoard/webserver.py
When returning a 500-error for GET we could've tried to access a `mimetype`
variable although one wasn't set.  Unify the way responses are created for
GETs and make sure we always set content-type and content-length.
> webserver: make sure content-type and content-length are defined

- pghoard/compressor.py
- pghoard/object_storage/google.py
- pghoard/object_storage/local.py
- pghoard/object_storage/s3.py
- pghoard/pghoard.py
- test/test_pghoard.py
Add timeline support for wal deletion and fix Google storage's deletion tracebacks.
> WAL cleanup fixes

- README.rst
- pghoard/archive_sync.py
- pghoard/basebackup.py
- pghoard/common.py
- pghoard/object_storage/azure.py
- pghoard/object_storage/google.py
- pghoard/object_storage/local.py
- pghoard/pghoard.py
- test/base.py
- test/conftest.py
- test/test_basebackup.py
- test/test_compressor.py
- test/test_pghoard.py
- test/test_transferagent.py
- test/test_webserver.py
Fixes basebackup pruning in object stores, improves testability of object stores and so on.
> Object store fixes

- pghoard/object_storage/google.py
This can be used to disable object caching, etc.
> google storage: allow passing custom storage properties

- .travis.yml
- pghoard/rohmu/object_storage/google.py
This occurs sometimes, when it does, retry for some time:
socket.gaierror: [Errno -5] No address associated with hostname
->
httplib2.ServerNotFoundError: Unable to find the server at www.googleapis.com
> rohmu: retry on www.googleapis.com dns error

- pghoard/transfer.py
This allows us to see which files of which type have been transferred
last just by glancing at the state file.
> transfer: Store the name of the latest file transferred

- .travis.yml
- NEWS
- README.rst
- pghoard/basebackup.py
- pghoard/rohmu/compat.py
- pghoard/rohmu/inotify.py
- pghoard/rohmu/object_storage/local.py
- pghoard/rohmu/object_storage/swift.py
- pghoard/transfer.py
- pghoard/webserver.py
- setup.py
- test/conftest.py
- test/test_encryptor.py
- test/test_wal.py
Includes Python 3.3 related changes from https://github.com/ohmu/pghoard/pull/93 but replaced the contextlib.suppress -> try/except changes with a suppress compat-module.
> Python 3.3 support

- README.rst
Includes contents of #101 with minor edits plus a new section about taking backups.
> README: backing up and restoring

- pghoard/rohmu/object_storage/google.py
Create a new context manager for the object client which resets the client
on server errors as well as provides a convinient way to map 404 Not Found
errors into our own exception type.
This should hopefully fix endless loops of errors like this:
May 12 07:48:54 c5981 pghoard[37]: Compressor Thread-5 INFO: Compressed and encrypted 16777216 byte open file '/var/lib/pgsql/9.6/data/pg_xlog/00000001000000000000000A' to 790301 bytes (4%), took: 0.063s
May 12 07:48:54 c5981 pghoard[37]: TransferAgent Thread-11 ERROR: Problem in moving file: '/var/lib/pgsql/9.6/data/pg_xlog/00000001000000000000000A', need to retry
May 12 07:48:54 c5981 pghoard[37]: Traceback (most recent call last):
May 12 07:48:54 c5981 pghoard[37]: File "/usr/lib/python3.4/site-packages/pghoard/transfer.py", line 163, in …
> google: reset client on server errors

- NEWS
- pghoard/basebackup.py
- pghoard/compressor.py
- pghoard/config.py
- pghoard/pghoard.py
- pghoard/restore.py
- pghoard/rohmu/__init__.py
- pghoard/rohmu/compressor.py
- pghoard/rohmu/encryptor.py
- pghoard/rohmu/filewrap.py
- pghoard/rohmu/object_storage/google.py
- pghoard/rohmu/rohmufile.py
- pghoard/rohmu/snappyfile.py
- test/base.py
- test/conftest.py
- test/test_common.py
- test/test_compressor.py
- test/test_encryptor.py
- test/test_pghoard.py
More generic data encryption, decryption, compression and decompression layers allowing easier stacking of things.  This will be used to implement a new parallel local backup mode in the near future.
> Refactored rohmu file interfaces

- README.rst
- pghoard/basebackup.py
- test/conftest.py
Superuser access is required to look up data_directory from PG.
> local tar backup: require pg_data_directory configuration

- pghoard/common.py
- pghoard/pghoard.py
- pghoard/wal.py
Commit 2a04eefa3d158f implemented a redundant suppress function in common.py
for no apparent reason.
> compat: use the suppress code from pghoard.rohmu.compat

- pghoard/transfer.py
Some object storages have frequent internal errors once in a while,
no point in logging those because of this ignore upload failures on
the first try.
> transfer: Ignore upload errors for statistics purposes on first try

- debian/pghoard.postinst
- debian/rules
These changes improve the debian package generated for pghoard:
- install the systemd unit
- create the /var/lib/pghoard folder with proper permissions
> Improve debian packaging

- pghoard/basebackup.py
pg_switch_xlog() is a superuser-only function before 9.6, and even in 9.6 it
would require an extra GRANT.  Use the pg_start_backup() and
pg_stop_backup() functions which we're able to call anyway to trigger the
xlog switch.  The downside is an unnecessary checkpoint.
> local-tar basebackups: use pg_start_backup() and pg_stop_backup() to switch xlog

- pghoard/basebackup.py
- test/conftest.py
- test/test_basebackup.py
We can't call the required functions on a standby.
> local-tar basebackup: don't try to get backup end segment name in recovery

- pghoard/restore.py
This allows to limit the maximum used temp space to a maximum
of transfer threads * chunk size.
> restore: Use same threadpool for both download/extraction

- pghoard-local-minimal.json
- pghoard/archive_cleanup.py
added dry run mode for archive cleanup
made file unavailability storage errors non-fatal
> dry run mode for archive cleanup

- pghoard/restore.py
When fetching backups new transfer object is created for each
individual backup file. For large restoration operations there can
be 1000+ files and the transfer objects can take several gigabytes
of memory and depending on the storage type each transfer may also
require one or more file descriptors (2 for GCS), possibly causing
the app to run out of fds. The objects are not needed until the
actual download begins so only create them at that point.
> Delay transfer object creation until start of download

- pghoard/transfer.py
- test/test_transferagent.py
In case the machine e.g. looses network connection upload will start
failing consistently. Since there may be multiple WAL files to upload
the old half a second sleep after failure might still mean the app
tries to make 40 or so uploads per second, which results in a lot of
log spamming. Increase the wait time for uploads that have failed
multiple times to reduce the spamminess.
> upload: Retry less frequently when upload keeps on failing

- pghoard/fetcher.py
- pghoard/pghoard.py
- pghoard/transfer.py
- pghoard/webserver.py
- test/conftest.py
- test/test_transferagent.py
- test/test_webserver.py
Earlier logic tried to prefetch WAL/history files that are expected to
be requested by PostgreSQL but because it waited for the prefetch ops
to complete before serving the original request it wasn't very
effective. Also, due to GIL the processing often ended up being CPU
bound.
To speed up the processing, make all file fetch operations run in the
background as identical jobs and just poll a queue of completed
operations to finalize the background jobs and in case one of them is
the operation that is currently expected to finish, fulfil the request.
New prefetch operations are always scheduled even if the current
request can be fulfilled without downloading anything so that there is
always a backlog of prefetch operations.
In addition to improving the prefetch logic, the file download, …
> webserver: Do proper concurrent WAL/history downloads

- pghoard/webserver.py
PostgreSQL seems to sometimes generate files to pg_wal directory that
don't match the contents of what should be in a file with such name. The
reason why this happens is unclear but based on investigating log files
it does not seem like PGHoard would be responsible for the creation of
these files or that it would otherwise have returned invalid data at any
point.
Earlier logic of skipping prefetch based on the existence of supposed
target file resulted in bad performance because when the file was really
being served the target file couldn't be utilized. Make the same check
during prefetch phase so that prefetch is performed if local data will
not be useful in serving the possible upcoming file request.
Also added some logging statements that are useful in determining the
sequence of …
> webserver: Prefetch pre-existing files if existing ones are broken

- pghoard/rohmu/object_storage/azure.py
The Azure SDK does not provide file data sequentially, which breaks with
the new implementation that expects to get sequential data from storage
so that the data can be directly fed through all transformations without
any intermediate storage. Add custom chunked download logic for Azure to
work around the SDK limitation.
> restore: Fix download in Azure

- pghoard/basebackup.py
- test/test_basebackup.py
Previously the directory create operations were only part of the tar
file that contained first file/dir under the directory. This resulted in
invalid permissions being set for the directories if later tar that did
not contain the permission information for the intermediary directories
was extracted before an earlier one.
Now all relevant directories are added to all of the tar files, ensuring
they can always be handled independently in any order.
> basebackup: Ensure each tar chunk contains all relevant information

- pghoard/restore.py
- test/test_restore.py
There has been at least one reported incident where downloading
basebackups stopped making progress for some reason. Root cause is not
known but presumably tearing down the worker pool and downloading all
files that were not reported as completed should fix the situation.
> restore: Restart downloaders in case basebackup download stalls

- requirements.txt
run the command `pip install -r requirements.txt` to have them properly installed
> add requirements.txt to ease development environment

- README.rst
- pghoard/mapping.py
- pghoard/monitoring/pushgateway.py
- pghoard/pghoard.py
> Send metrics to a Prometheus Pushgateway

- pghoard/rohmu/object_storage/local.py
- test/test_storage.py
Basebackup restoration keeps track of progress being made with the
restoration and if there's no progress in two minutes it assumes that
something has failed and restarts the restore process. Local storage
implementation did not implement progress reporting so for very large
files the timeout could be reached before an individual file got
copied, failing the restoration. Make local storage report progress as
well to avoid that.
> rohmu: Report progress for local file transfers

- pghoard/restore.py
- test/test_restore.py
When calling restore from another program, getting basebackup
download status information in machine-readable format (instead of
parsing log output from stdout) makes monitoring and implementing
custom metrics easier.
> restore: add status file output support

- pghoard/rohmu/compressor.py
- pghoard/rohmu/encryptor.py
- pghoard/rohmu/filewrap.py
- pghoard/rohmu/object_storage/azure.py
- pghoard/rohmu/object_storage/base.py
- pghoard/rohmu/object_storage/google.py
- pghoard/rohmu/object_storage/local.py
- pghoard/rohmu/object_storage/s3.py
- pghoard/rohmu/rohmufile.py
- test/conftest.py
- test/test_compressor.py
- test/test_encryptor.py
- test/test_storage.py
Also support streaming compression and encryption that can be applied directly to input source such as file in order to upload the source stream in compressed and encrypted format without any intermediate local storage.
> rohmu: Support uploading stream of data

- pghoard/basebackup.py
If I ran out of disk space on the local file system, while pghoard was trying to do a base backup via pipe, it would fail, but then immediately try again, fail, try again and so on until it used up all the wal listeners.  But all of the pg_basebackup processes would remain running.
This fix just ensures that the failed process is properly killed off, it does not try to get smart and actually stop trying to do a base backup, that is something I think probably needs to be catered for with monitoring.
> ensure that a OS Error will be properly cleaned up

- pghoard/webserver.py
- test/test_webserver.py
There have been cases where a file that looks to be what PostgreSQL is
requesting already exists on disk but for some reason the file is not
acceptable and PostgreSQL keeps on requesting the same file again and
again. The version in object storage may be different and something that
PostgreSQL accepts so if we have already recently returned the requested
file from disk try object storage instead.
> Fetch data from cloud storage if same file is requested again

- pghoard/monitoring/statsd.py
- pghoard/wal.py
- test/test_wal.py
Updated the pghoard statsd exception metrics to match the prometheus name.
Created a more specific exception for wal verification failure.
> Improve exception logging

- .gitignore
- .travis.yml
- Makefile
- requirements.dev.txt
- requirements.txt
- setup.py
Run a full build matrix of Python versions/PostreSQL version when running CI.
> travis: Run full matrix tests during CI

- pghoard/transfer.py
Add logging at INFO level for file upload/download operations and delete operations (included within upload ops).
> INFO level logging of file upload/download operations

- pghoard/rohmu/object_storage/azure.py
- test/test_storage.py
See commit for up-to-date comment (seems to live too much).
> pghoard: Azure upload uses tell method

- pghoard/rohmu/compressor.py
An exception is instantiated, but then not raised -> has no effect.
> pghoard: raise the exception that is created

- pghoard/rohmu/object_storage/azure.py
The function failed when asking metadata for a file name that was a
prefix for other file or path names.
> azure: Fix get_metadata_for_key

- README.rst
- pghoard/rohmu/object_storage/azure.py
Extend proxy support to azure driver.
> rohmu/azure: support connectivity through proxies

- Makefile
- pghoard/basebackup/base.py
- pghoard/basebackup/chunks.py
- pghoard/basebackup/delta.py
- pghoard/common.py
- pghoard/restore.py
- pghoard/transfer.py
- test/basebackup/test_delta.py
- test/test_common.py
- test/test_pghoard.py
- test/test_restore.py
- test/util.py
Fixes the issues that appeared with Rohmu 2.0.1.
To be noted that it requires the following changes on rohmu's side: https://github.com/Aiven-Open/rohmu/pull/150 and hence, it will not pass until a new Rohmu version can be released.
> Fix type hints issue from Rohmu 2.0.1

- .github/workflows/codeql-analysis.yml
Updates CodeQL Github Workflow. 
Also minor reformat for the yml file.
> Fix CodeQL workflow ; v1 was deprecated and is now failing

- pghoard/webserver.py
Fix a pylint error by shortening a code line that is too long.
> Reduce the length of log debug line

- pghoard/pghoard.py
- pghoard/receivexlog.py
Reverts Aiven-Open/pghoard#642
> Revert "Use --no-sync for pg_receivewal"
