Aiven-Open/pghoard

pghoard/common.py
test/test_common.py

We used to just append lines to .pgpass when the entry did not already exist
there.  This didn't work when password was changed as previous lines with
the same host, port, dbname, user combo were not removed.

common: make pgpass file update more robust

---

pghoard/restore.py
test/test_restore.py

PostgreSQL doesn't require primary_conninfo in recovery.conf if
restore_command is given.  We did not require it in pghoard's restore but
always wrote a line for it (with empty value) if it wasn't given.
PostgreSQL doesn't like that so stop doing it.

restore: make primary_conninfo optional

---

pghoard/basebackup.py
pghoard/pghoard.py

Also in basebackup, make sure we actually have the basebackup tar
before trying to parse it.

pghoard: when running quit(), also stop any running basebackup processes

---

pghoard/errors.py
pghoard/object_storage/__init__.py
pghoard/object_storage/s3.py

Restore used to print out large and scary looking tracebacks when a file was
missing from storage.  Downgrade file not found errors in S3 (and other
object stores later on) to warnings as it's expected that restore ends in
the "last" file missing.

restore: don't print tracebacks when file doesn't exist in s3

---

pghoard/restore.py

The rationale behind this is to simplify the code and to allow direct
use of the configuration file. This will help in upcoming features
like adding of encryption/decryption for WAL and basebackups.

restore: remove object store specific commands and use a config

---

pghoard/webserver.py
test/test_transferagent.py
test/test_webserver.py

Decompress on metadata change had a bug on metadata handling in WAL restore from local directory. This change 1) reads the metadata from the correct location and 2) uses a correct metadata key for compression.
A test is updated to verify the data is handled correctly.

webserver: fix metadata handling on local WAL restore

---

pghoard/encryptor.py
pghoard/object_storage/s3.py

Accept encryption keys as both str and bytes. The latter is expected by the cryptography library but the former tends to be the format how stuff is passed around in configuration files.
The second fix is an symbol import fix for non-AWS but S3 compatible object storages.

two small fixes

---

pghoard/encryptor.py
test/base.py
test/test_encryptor.py

Contrary to the documentation, TarFile does perform seeks around the underlying fileobj.
Since there's no easy access to cipher state, we can only simulate backward seeks via restart and progress forward.

encryptor: implement seek in DecryptorFile

---

pghoard/object_storage/s3.py

Bypass but warn about bucket validation errors for S3. Bucket validation requires AWS IAM ListObjects permissions to the whole bucket without prefix limitations. In some cases, it may make sense to disallow listing of objects on bucket level, and e.g. allow listing for objects in apriori known pghoard site.

s3: bypass bucket validation errors to support stricter bucket ACLs

---

pghoard/compressor.py
pghoard/object_storage/__init__.py
pghoard/object_storage/azure.py
pghoard/object_storage/google.py
pghoard/object_storage/s3.py
pghoard/pghoard.py
pghoard/restore.py
test/test_webserver.py

Add support for optional path prefixes for stored content. This allows some organization of pghoard backups within a shared storage.

storage: support path prefixes when storing content

---

pghoard/object_storage/__init__.py
pghoard/object_storage/azure.py
pghoard/object_storage/base.py
pghoard/object_storage/google.py
pghoard/object_storage/local.py
pghoard/object_storage/s3.py

Add a new optional object storage configuration key `prefix` to allow
prefixing all operations in the store with a custom prefix.  This
supplements the per key prefixes that we already have and makes it easier to
further subdivide a common S3 or Google bucket.

object_storage: add optional prefix to storage configuration

---

.travis.yml
pghoard/postgres_command.py
test/conftest.py
test/test_webserver.py

Retry socket.errors two times before giving up. We shouldn't fail hard in case pghoard is restarted, or in case a system starts up and PostgreSQL tries to start recovery immediately from a pghoard that hasn't started up yet.

Retry for restore_command

---

.pylintrc
.travis.yml
Makefile
README.rst
pghoard.spec
pghoard/compressor.py
pghoard/create_keys.py
pghoard/encryptor.py
pghoard/object_storage/__init__.py
pghoard/pghoard.py
pghoard/restore.py
pghoard/webserver.py
test/test_transferagent.py
test/test_webserver.py

Prefetch files when performing archive recovery using pghoard's restore command against the local pghoard webserver.  The default is to start up to 'lower of Compression or Transfer Agent threads minus one' prefetch operations so we can perform all operations (original request + prefetch) fully in parallel without having to wait for threads to start.
We maintain a negative cache for "file not found" prefetch failures to avoid trying to prefetch the same files multiple times, but the cache isn't used for explicit download requests as the segments may show up in the archive after the first failures.
This speeds up archive recovery a bit in default configurations, but it may make sense to increase thread counts beyond the current defaults (5) if the store is slow or has high latency.

webserver: prefetch files on restore

---

pghoard/wal.py
pghoard/webserver.py
test/test_wal.py
test/test_webserver.py

PostgreSQL doesn't switch to a new xlog immediately after timeline change so
a wal file can contain records for multiple timelines.  Only consider the
log segment numbers when checking headers against filenames.

wal header check: allow different timelines in wal headers

---

pghoard/pghoard.py
test/conftest.py
test/test_basebackup.py
test/test_pghoard.py

Clean up previous basebackup threads once they finish to make sure we take
new basebackups when needed, but make sure we reset time of last check when
a new backup is taken to avoid taking too many backups too quickly.  Also
updated tests to handle more cases.

basebackups: make sure more basebackups are taken while running

---

pghoard/pghoard.py
test/conftest.py
test/test_basebackup.py
test/test_pghoard.py

Clean up previous basebackup threads once they finish to make sure we take
new basebackups when needed, but make sure we reset time of last check when
a new backup is taken to avoid taking too many backups too quickly.
Cleaning up basebackups is now done based on backup start time instead of
backup name, which is not guaranteed to increment alphabetically.
Also updated tests to handle more cases.

basebackups: make sure basebackups are taken and cleaned in a timely manner

---

pghoard/pghoard.py

time.monotonic() starts from zero at boot up, so don't rely on
time.monotonic() - 0 being above 60.

pghoard: make sure we refresh times of last backups at startup

---

Makefile
README.rst

Also changed Pyhon version in the example egg name from 2.7 to 3.4 as we
don't even support Python 2 anymore.

README, rpm: update rpm building instructions

---

README.rst
pghoard/archive_sync.py
pghoard/basebackup.py
pghoard/compressor.py
pghoard/pghoard.py
pghoard/restore.py
pghoard/rohmu/compressor.py
pghoard/wal.py
test/test_basebackup.py
test/test_pghoard.py
test/test_webserver.py

Previously we first stored the basebackup onto disk after which we
compressend and encrypted it. This meant we'd need roughly 2.5x
diskspace (1 copy in the running db, 1 as a cleartext tempfile and
~0.5x for the compressed encrypted copy).
This drops the requirement to roughly ~1.5x (1 running copy and a
second temporary compressed and encrypted one. Eventually we should
just create a stacked encryptor/compressor that would take a fp as
an input and give out a stacked file handle that you could read from
to write into an object storage.

basebackup: support encrypting and compressing basebackups on the fly

---

Makefile
version.py

This allows one to build the tarballs github serves for our tags.

version.py: use short_ver from Makefile if nothing else is available

---

Makefile
setup.py
version.py

Instead of passing Makefile's version to setup.py in env when called from
make, read it from Makefile in version.py.  This allows us to use the
version even when we're calling setup.py directly without invoking make.
We'll also be careful about version numbers provided to setup.py: git tags
aren't accepted by pkg_resources so we'll just use the commits since tag as
a `.devN` tag.
Also make sure setup.py and version.py work correctly when called from a
working directory outside pghoard root.

setup.py: more changes for version and setup handling

---

pghoard/basebackup.py
pghoard/common.py
pghoard/rohmu/compressor.py

This prevents the stderr buffer from filling, and lets us have a view of the
basebackup progress.

basebackup streaming: read stderr and log it at debug level

---

README.rst
pghoard/basebackup.py
pghoard/common.py
pghoard/compressor.py
pghoard/pghoard.py
pghoard/restore.py
pghoard/rohmu/__init__.py
pghoard/rohmu/compressor.py
pghoard/rohmu/object_storage/local.py
pghoard/rohmu/object_storage/swift.py
pghoard/transfer.py
test/test_compressor.py
test/test_storage.py

Many Swift implementations require objects > 5 gigabytes to be segmented so
implement segmenting in the Swift driver with a default segment size of 1
gigabyte.  Smaller files are uploaded as before, but larger files are split
into 1 gigabyte chunks by default.

swift: segmented transfer support

---

NEWS
pghoard/postgres_command.py
test/test_webserver.py

PGHoard does not use backup labels, but currently PG tried to archive them
through PGHoard whenever it was in archive mode which would hang
indefinitely.

postgres_command: ignore backup label archive requests

---

NEWS
pghoard/rohmu/object_storage/s3.py

For files larger than 100MB we start splitting transfers into 100MB
upload chunks. The idea is to gain resiliency in the face of network
errors when uploading large files.

s3: Add support for multipart uploads to AWS S3 buckets

---

NEWS
README.rst
pghoard/compressor.py
pghoard/config.py
pghoard/rohmu/compressor.py
test/test_compressor.py

Previously it was hardcoded to zero, default to that but allow
users to override the compression level.

compressor: Make LZMA compression level configurable

---

README.rst

Turns out that basebackup_interval_hours has a default value, update README accordingly.

README: fix basebackup_interval_hours description

---

pghoard/basebackup.py
test/test_basebackup.py

Also enhance existing unittest for stream-compression to check
for the its existence.
This is needed since stream-compression bypasses Compressor where
we usually set the pg-version.

basebackup: When using stream compression store pg-version into metadata

---

NEWS
pghoard/pghoard.py
test/test_pghoard.py

Previously startup_walk_for_missed_files didn't consider compressed and
uncompressed incoming files (ie files received by receivexlog) separately
and tried to recompress already compressed files and left uncompressed files
alone.

startup_walk_for_missed_files: handle compressed and uncompressed files

---

NEWS
pghoard/wal.py

We need to recognize the magic number from WAL to archive it.

wal: add 9.6 beta1 wal magic number

---

pghoard/wal.py

Since we have to store the pg_version in the object store file
metadata as a string, ensure it's an integer.

wal: Ensure that the pg_version given is an integer for comparison

---

README.rst
pghoard/compressor.py
pghoard/pghoard.py
pghoard/statsd.py
pghoard/transfer.py
test/test_compressor.py
test/test_transferagent.py

The initial version just sends unexpected exception info
to the external statsd.

statsd: statsd output support

---

README.rst
debian/control
pghoard.spec

Specifically note that cryptography 0.8+ is required, and add that
requirement to the relevant packaging scripts.
Also change some cases of ``pghoard`` to PGHoard when we're talking about
the backup software suite instead of the actual daemon process.

README: document requirements and reword some paragraphs

---

pghoard/basebackup.py
pghoard/patchedtarfile.py
pghoard/restore.py

* Monkey-patch tarfile to increase buffer size for file copying from 16KiB
to 2MiB
* Don't use "|" in mode when writing - it's really only useful when using
tarfile's internal compression handling, and causes unnecessary extra
buffering (in 10KiB buffers by default)
* When reading tar files (pghoard_restore get-basebackup) we need to use
tarfile's stream buffer management until rohmu's SnappyFile interface
supports buffering and seeks.  To make it less slow increase the buffer
size to something reasonable

backup and restore: improve tar handling performance

---

README.rst

This fixes #134 
There are other ports (e.g `http_port`) in config that do not cast str value to integer.

Fix statsd README typo

---

README.rst
pghoard/pghoard.py
pghoard/statsd.py

Small patch to add support for DataDog statsd format.
I also tried to use Telegraf format to send stats to Datadog, in general it works, but metric name was set based on tags, but tags are in python dict, so there is no strict order, sometimes it was: `pghoard.last_upload_age_type_basebackup_site_foo` next time `pghoard.last_upload_age_site_foo_type_basebackup`.

Add support for DataDog statsd format

---

pghoard/rohmu/object_storage/google.py

I found when running the included tests I got this error:
python3 -m pylint.lint --rcfile .pylintrc pghoard/ test/
************* Module pghoard.rohmu.object_storage.google
R:182,24: Redefinition of next_prog_report type from int to float (redefined-variable-type)
make: *** [pylint] Error 8
The following patch resolves this issue.

Define next_prog_report as float in pghoard/rohmu/object_storage/google.py

---

.travis.yml
NEWS
README.rst
pghoard/rohmu/object_storage/azure.py
pghoard/rohmu/object_storage/base.py
test/test_storage.py

Azure-storage-python had in the meanwhile changed the names of
multiple methods and changed the behavior around listing of files.
Azure no longer accepts hyphen's '-', we replace them in metadata
now with an underscore '_' and then replace them back when doing
blob listings.
Also improve error handling so missing files are handled gracefully,
and add Azure to the list of tested storage backends. The storage
completes the tests successfully after this commit.

azure: Make Azure support work with latest azure-storage-python

---

pghoard/rohmu/object_storage/azure.py
test/test_storage.py

The blob.metadata object apparently is empty, we need to fetch the
actual metadata for the blob with a metadata listing call.
Also add a unit test to cover the case of fetching
metadata with get_contents_to_string.

pghoard: Fix Azure metadata fetching when fetching directly to memory

---

.gitignore
README.rst
pghoard/rohmu/object_storage/s3.py
test/test_storage.py

This PR (a redo of #150) implements optional support for S3 server-side encryption. It also fixes the S3 tests which, as far as I can tell, currently do not work for two reasons:
1. The `bucket.list(path)` method includes the path itself in the response but the tests assert a length of the return value that only contains the keys added to the path. The implementation of `list_path` is updated to discard the element for path.
1. The test code to inject a failure into the S3 upload does not work. The `new_key` method isn't called during the upload. The test code also assumes a multipart upload will happen but the production code is using the non-multipart upload path. The `store_file_from_disk` implementation now always uses a multipart upload if the multipart argument is True. Otherwise …

S3 encryption support

---

pghoard/basebackup.py
pghoard/common.py
pghoard/pghoard.py
pghoard/wal.py
test/test_common.py

While .pgpass use has been convenient it has had the unfortunate
side issue of having yet-another-place where to store the user credentials.
Since we don't absolutely need it, lets get rid of it.

pghoard: Get rid of .pgpass file use for security reasons

---

NEWS
pghoard/basebackup.py
pghoard/rohmu/inotify.py
test/test_basebackup.py

When `local-tar` basebackups are used in exclusive mode (PG <= 9.5 without
pgespresso) any conflicting exclusive basebackup is automatically cancelled
to allow PGHoard to take its own basebackup.  This is sometimes required if
a previous PGHoard process has been killed while it was taking a backup.

local-tar basebackup: abort a conflicting exclusive backup if one is running

---

pghoard/pghoard.py

a) It's a good idea to clean up old dead threads from the background
b) it makes pghoard notice that it's missing a pg_receivexlog for a site
in case a pg_receivexlog process has been killed. (by OOM killer for example)

receivexlogs: Get rid of old dead receivexlogs

---

NEWS
README.rst
pghoard/config.py
test/test_pghoard.py

In case of a machine with many CPUs try to set a better default than
5 as the threadcount. Now it's set to max(cpu_count, 5).

pghoard: Set compression/transfer thread defaults based on cpu count

---

NEWS
pghoard/basebackup.py
pghoard/restore.py
test/test_basebackup.py

Basebackup `end-time` and `end-wal-segment` are now stored in metadata and
used for PITR when `local-tar` basebackups are used.
When performing recovery to a given point the point must be after the end of
the backup, so try to store such a time in the metadata.  The pg_basebackup
methods don't currently store it as there's no way to get it over a
replication protocol.  We'll probably require a non-replication connection
to the db in the future for all basebackup types.

basebackups: store backup end time and segment in metadata in local-tar mode

---

pghoard/webserver.py
test/test_webserver.py

Previously during recovery if we reached a recovery target and restarted
PostgreSQL, pghoard would refetch all xlog files since the last checkpoint
again. Now we check if we already have them and just use them as-is.

webserver: don't refetch xlog files if we happen to have them already

---

pghoard/rohmu/encryptor.py

Workaround for random SSL-related hangs.
https://github.com/pyca/cryptography/issues/2911

pghoard: workaround for cryptography deadlock bug

---

pghoard/basebackup.py
pghoard/pghoard.py
pghoard/restore.py
pghoard/rohmu/dates.py
pghoard/rohmu/object_storage/google.py
pghoard/rohmu/object_storage/s3.py
pghoard/rohmu/object_storage/swift.py
test/test_basebackup.py
test/test_rohmu_dates.py

Previously we just used `dateutil.parser.parse` to handle timestamps, but
that's not really good enough as we can't be sure whether or not we get a
valid timezone back, and when we're comparing `datetime` objects they must
all be either tz-aware or tz-naive.
This commit implements a new helper function that parses timestamps using
`dateutil.parser.parse` and then either makes sure that the resulting object
*does* or *does not* include a `tzinfo`.
This fixes a bug where the timestamp parsed from a basebackup's
`backup_label` wasn't recognized and we ended up with a naive `datetime`
which later on would cause errors when it was being compared to other
tz-aware `datetime` objects.

dates: start using a tz-aware helper function for parsing timestamps

---

pghoard/pghoard.py
pghoard/rohmu/object_storage/google.py

Google Cloud library sometimes fails with a BrokenPipeError and the
next request is successful.

pghoard: retry on google api BrokenPipeError

---

README.rst
pghoard/rohmu/object_storage/swift.py

Support for OpenStack Swift auth version 3. Tested only against auth version 3, don't have access to 1 or 2.

OpenStack Swift auth version 3 support #193

---

README.rst

Update the README to show correct default values for ``pg_receivexlog``, ``alert_file_dir``, and ``basebackup_count``.

fix default config values in README

---

pghoard/rohmu/object_storage/s3.py

S3 multipart file uploads that have more than 1000 chunks fail due to `boto`
paginating the results of `multipart_upload.get_all_parts()` to 1000.  The
`boto` docs recommend using the `MultiPartUpload` object as an iterator instead
so that pagination happens automatically.
http://boto.cloudhackers.com/en/latest/ref/s3.html#module-boto.s3.multipart

fix s3 multipart upload to account for more than 1000 parts

---

test/test_webserver.py

The test_handle_site in test_basebackup created the same WAL file
and if it was run before test_get_encrypted_archived_file the test
would fail since it would return the pre-existing data.
The reason the data passes the webserver code's prefetch correctness
checks is that it really had the correct WAL file header.

tests: Fix webserver unittest failure by using a different WAL segment

---

pghoard/config.py
pghoard/pghoard.py

The README mentions a maintenance mode file.  This PR adds a default config value and checks for the file when determining if a new base backup is needed.

prevent backups when maintenance mode file exists

---

pghoard/rohmu/object_storage/s3.py

Allows for using s3 object storage with IAM role authentication.
Currently my docker image is running below code in an additional layer as all our authentication is done using IAM roles.
```
RUN sed -i -r 's/ +aws_access_key_id,//' /usr/lib/python3.6/site-packages/pghoard/rohmu/object_storage/s3.py \
&& sed -i -r 's/ +aws_secret_access_key,//' /usr/lib/python3.6/site-packages/pghoard/rohmu/object_storage/s3.py \
&& sed -i -r 's/encrypted=False\):/encrypted=False,aws_access_key_id=None,aws_secret_access_key=None):/' /usr/lib/python3.6/site-packages/pghoard/rohmu/object_storage/s3.py
```
Closes #213

Allow for usage of IAM roles

---

Makefile
NEWS
golang/pghoard_postgres_command_go.go
pghoard.spec
test/test_basebackup.py

Running the Python3 `pghoard_postgres_command` for Postgres's restore_command takes around 0.3 seconds just to send a message to a local HTTP server.  Reimplemented the restore_command parts of postgres_command in Go for faster startup times.
If this looks like something we'll merge we can extend the command In the future to also automatically handle prefetched and already existing files.

pghoard_postgres_command_go.go: reimplementation in go for faster startup time

---

NEWS
pghoard/restore.py

`pghoard_restore` can now download and extract chunked basebackups using
all CPU cores of the machine assuming that the parallel download mechanism
can deliver it chunks fast enough.

restore: make it parallel using ThreadPoolExecutor

---

pghoard/config.py
test/test_compressor.py
test/test_pghoard.py

Try to run more transfer agents in parallel with low cpu counts to better
utilize network resources and to work around issues where one transfer
stalls for a while.

config: adjust default thread counts for transfer and compression

---

pghoard/archive_cleanup.py
pghoard/config.py
pghoard/restore.py
test/base.py

We're just trying to retrieve a basebackup there's no point in trying to
read a version file from the empty directory.  Also, archive_cleanup doesn't
really need it either so disable the check there, too.

config: don't require pgdata to have a version if we're running pghoard_restore

---

Makefile
test/conftest.py
test/test_basebackup.py
test/test_compressor.py

Also adds a missing build-dep-fed azure dependency.
test/test_basebackup.py::TestPG
cannot collect test class 'TestPG' because it has a __init__ constructor
test/test_compressor.py::TestWAL
cannot collect test class 'TestWAL' because it has a __init__ constructor

tests: rename TestPG and TestWAL so not to confuse pytest

---

pghoard/rohmu/object_storage/google.py

IncompleteRead seems to be quite common when fetching larger objects. Without this change we were completely unable to restore a large base-backup without hitting it in all our attempts (We tried multiple instances and multiple base-backups).

Retry on Google Cloud Storage IncompleteRead errors

---

pghoard/compressor.py
pghoard/pghoard.py
pghoard/walreceiver.py
pghoard/webserver.py
test/test_compressor.py

Also update tests and internal signaling to use only MOVE
events for WAL files.

pghoard: Only handle MOVE events when handling WAL events

---

Makefile
pghoard/basebackup.py

We've seen a few cases where a checkpoint doesn't come along and
we have to wait for extended periods of time. Checkpointing at
backup time (i.e. once a day or so) should be fine.

basebackup: use pg_start_backup with fast flag, forcing a checkpoint

---

NEWS
README.rst
pghoard/archive_cleanup.py
pghoard/compressor.py
pghoard/config.py
pghoard/pghoard.py
pghoard/restore.py
pghoard/transfer.py
test/test_basebackup.py

This allows overriding the path where a site's backups are stored:
previously we always used the name of the site for this, optionally
prefixed by an undocumented top-level `path_prefix` key.

backup sites: add a new configuration option `prefix`

---

pghoard/archive_sync.py

Went to use this command today and the help text seemed to contradict the option in my mind... I think this is clearer and it matches the `--no-verify` flag's intent.

Update archive_synce --no-verify help message

---

.travis.yml

Pylint 1.8.1 has a bug https://github.com/PyCQA/pylint/issues/1773 that breaks with bare exception re-raises. Pin to a specific working version until the fixed pylint is available on PyPI.

travis: pin pylint to version 1.7.4 and astroid 1.5.2

---

.travis.yml
Makefile
NEWS
README.rst
pghoard.spec
pghoard/rohmu/object_storage/s3.py
test/test_storage.py

Use botocore rather than boto for interfacing with S3. Botocore is the undelying library under boto3 and is actively maintained.
E.g. at the time of writing, botocore support the new eu-west-3 region, while boto is still lacking definition for it.

s3: switch to using botocore from boto

---

pghoard/restore.py

Previously we just checked if the variable was there, we should
check if it really is a directory that it's pointing to or not.

pghoard: check for existence of tablespace path, not variable

---

pghoard/pghoard.py
test/test_pghoard.py

The rationale is to reduce the need for making connections to
the PG server to only query information we already know.

pghoard: cache pg_version per site, so we don't have to recheck it

---

.travis.yml
pghoard/webserver.py

Pre-existing WAL files whose contents don't match the name of the file
is a normal condition that can happen very often so don't log warning
every time such situation occurs. Having a lot of bogus warnings makes
it more difficult to spot real errors.

webserver: Reduce logging when prefetching WAL files

---

pghoard/transfer.py
pghoard/webserver.py

If a download has taken longer than it should, a new download operation
for the same file is started. Previously this overwrote the expected
name of the temporary file that shall be created by the download. This
caused problems if the earlier download did eventually finish and it
also finished before the newly scheduled download. The result handler
was called for the first download as well but instead of using the
original temp file name it used the second download's temp file name,
which was still in progress and the file was empty.
The operation was retried for 30 seconds and future downloads might
have succeeded but depending on timing conditions there could've been
multiple failures and the download failed permanently, causing WAL
restoration to fail.
Currently missing unittest for …

webserver: Fix handling of timed out downloads

---

pghoard/rohmu/object_storage/azure.py
pghoard/rohmu/object_storage/base.py
pghoard/rohmu/object_storage/google.py
pghoard/rohmu/object_storage/local.py
pghoard/rohmu/object_storage/s3.py
pghoard/rohmu/object_storage/swift.py

While PGHoard itself does not currently require this method, the object
storage abstraction it provides can be used by other applications that
would benefit from having such functionality available.

object storage: Add method for getting file size

---

pghoard/pghoard.py

Helps the test mock code trigger the expected behavior without by
setting the time_of_last_backup_check value to zero and thus avoiding
the 300 second wait.

pghoard: zero time_of_last_backup_check value considered as not checked

---

pghoard/pghoard.py

When changing object storage, pghoard would have to be restarted in order to use
the new object storage. The reason for this is that the TransferAgent would never read the
new value from the config if it already had a value stored in memory. This commit clears that value
and makes sure it gets forced to load the new value from the config.

pghoard: object storage change support

---

pghoard/basebackup.py

PGHoard generates basebackup names locally based on timestamp and a running counter.
In scenarios when basebackup are created on a new host during the same day as an earlier basebackup
was created on an older host, the old basebackup will end up overwritten and preventing recovery from that period.
Proposed change is to change the basebackup naming from %Y-%m-%d_{COUNTER} to %Y-%m-%d_%H-%M which should solve this problem.

pghoard may overwrite existing basebackup when taking a new one

---

pghoard/basebackup.py

Finding unique folder did not work correctly because the method only
attempted new folder name when current minute changed.

Partially restore old index logic for basebackup directories

---

pghoard/rohmu/object_storage/s3.py

botocore will not accept an input of type memoryview, only
bytes or bytearray objects.

s3: when storing an object from memory, cast it to bytes

---

pghoard/pghoard.py

Filter Metadata's keys from S3.
Minio S3 implementation return metadata with uppercase letters ( first ones ), triggering a bug in pghoard that cannot find the key ( KeyError )
This simple patch simply convert the keys of the metadata dict to lower case, solving it all .

Filter Metadata's keys from S3.

---

pghoard/rohmu/object_storage/azure.py
pghoard/rohmu/object_storage/base.py
pghoard/rohmu/object_storage/google.py
pghoard/rohmu/object_storage/local.py
pghoard/rohmu/object_storage/s3.py
pghoard/rohmu/object_storage/swift.py

When using rohmu as a standalone component being able to set mime type
for the uploaded files is sometimes relevant so allow doing so.

rohmu: Allow setting mime type for uploaded files

---

pghoard.spec

We had a dependency on postgresql-server to be able to create an empty
/var/lib/pghoard which is owned by the postgres user.  This may have been
convenient, but not really necessary as a user will have to manually set up
configuration and state anyway, so let's drop it to avoid needing a hard
dependency on postgresql-server.

rpm spec: remove dependency on postgresql-server

---

pghoard/rohmu/encryptor.py

For some reason pylint does not like these.

encryptor: remove duplicate len() statements

---

pghoard/rohmu/object_storage/base.py
pghoard/rohmu/object_storage/local.py
pghoard/rohmu/object_storage/s3.py
test/test_storage.py

These changes allow better emulation of cloud storages using local file storage. Previously some use cases could not be supported with local file storage and many cases did not work properly in case of concurrent access to the local storage.

Support delete tree, race condition fixes for local file storage

---

pghoard/restore.py
pghoard/rohmu/encryptor.py
test/test_restore.py

This fixes the issue reported at https://github.com/aiven/pghoard/issues/309
The patch makes sure that the actual basebackup file size is passed to the DecryptSink, which can then decrypt the backup with no errors.

File size is required in order to decrypt a basebackup with DecryptSink.

---

README.rst
pghoard/mapping.py
pghoard/metrics.py
pghoard/monitoring/prometheus.py
pghoard/pghoard.py
pghoard/webserver.py
test/conftest.py
test/test_webserver.py

This PR adds an endpoint (`/metrics`) to the embedded webserver to expose Prometheus metrics.

Expose Prometheus metrics through a HTTP endpoint

---

README.rst

Clarify that this tooling backs up *to* cloud object stores, not that it can backup cloud object stores into pg (which only makes sense for small stores, of course).

Clarify intro sentence

---

pghoard/rohmu/object_storage/azure.py
pghoard/rohmu/object_storage/base.py
pghoard/rohmu/object_storage/google.py
pghoard/rohmu/object_storage/local.py
pghoard/rohmu/object_storage/s3.py
test/test_storage.py

All storage providers support performing a remote copy operation, which
can be useful if an object has already been uploaded but another copy of
the same data is needed with different name / metadata.

rohmu: Add support for remote copy operation

---

README.rst
pghoard/archive_sync.py
pghoard/compressor.py
pghoard/config.py
pghoard/fetcher.py
pghoard/rohmu/rohmufile.py
pghoard/transfer.py
pghoard/webserver.py
test/test_archivesync.py
test/test_compressor.py

Previously archive sync only verified file existence in remote file
storage but in some cases the files may be present but invalid. E.g.
in case old master is replaced because it became unresponsive the node
might still be running but just very slowly and it could manage to
upload WAL file for old timeline that is invalid but new master didn't
replace the file with a valid one because it was happy with the fact the
file exists even though it wasn't usable.
SHA1 was used due to its availability in Python's built-in hashlib. Some
other hashes might be more suitable due to better throughput but even
for very busy environments the performance of SHA1 should be good enough
not to cause noticeable extra load so the extra overhead of using hash
that doesn't ship with Python isn't worthwhile. …

Keep track of WAL SHA1 hashes to allow verifying contents

---

NEWS
README.rst
pghoard/basebackup.py

Commit d97c10b989 switched to fast checkpoints on pg 9.6 and newer, but didn't pass the memo to the older pg_start_backup() variant used in pg 9.5 and older.

Use fast checkpoints in PG 9.5 and below

---

.travis.yml
requirements-zstd.txt
requirements.txt

By default python-zstandard setup builds zstd binary from the sources included in repo.
"--system_zstd" build parameter controls whether to compile against the system zstd library.
For this to work, the system zstd library and headers must match what python-zstandard is coded against exactly.

ci: run zstd tests on all platforms.

---

README.rst

The restructedText format was invalid, causing pypi to reject it

Add missing linefeed to readme

---

Makefile
pghoard.spec

In Fedora 30 and newer dependencies are generated automically from egg/dist metadata.
We don't want that as we already specify required depedencies in .spec file.
In earlier Fedora versions automatic dependency generation was disabled by default.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/

rpm: disable automatic dependency generation

---

README.rst
pghoard/config.py
pghoard/receivexlog.py
test/conftest.py
test/test_pghoard.py

If PGHoard temporary directories reside on a different volume than the
PostgreSQL data directory itself that volume may fill up if the rate at
which new WAL files are being generated is higher than WAL processing
and upload speed. To cope with such situations, allow sending SIGSTOP
and SIGCONT to pg_receive(xlog|wal) to temporarily pause processing so
that uploads can catch up.

receivexlog: Allow pausing xlog/WAL receiving when disk space is low

---

test/test_pghoard.py

Processing all the WAL files can take a while because there's one
second delay each time pg_receivewal is suspended and depending on
how many times it gets suspended the test might not complete within
the previous max time. Drop segments to 15 to make the test faster
and allow it to take longer time. 15 should still be plenty to make
the disk fill up if the logic doesn't work.

Tune test_pause_on_disk_full settings to fix transient failure

---

README.rst
pghoard/config.py
pghoard/pghoard.py
test/test_pghoard.py

Often it is desirable to keep backups for certain period of time. The
backup count setting does allow emulating that to an extent but it does
not work correctly when new basebackups are created manually, in which
case the total count will be exceeded and backups are deleted before
the desired maximum age.

Allow restricting basebackups based on backup age

---

README.rst
pghoard/basebackup.py
pghoard/pghoard.py
test/test_basebackup.py
test/test_pghoard.py

Previously new basebackup was always taken "backup interval" hours
after the previous one. This made it difficult to set up backups so
that they are created at a time when the system is under least load
and the backup time kept on drifting and any manual backups
completely changed it.
This commit introduces basebackup_hour and basebackup_minute settings.
When those are present basebackups are created at that exact time
unless previous scheduled basebackup was created fairly recently, in
which case at least half of backup interval is waited until next
backup is created to avoid backups very close to each other in case
backup time settings are changed. Manual backups don't affect the
backup schedule.

Allow defining schedule for basebackups

---

pghoard/pghoard.py
pghoard/webserver.py
test/test_pghoard.py
test/test_webserver.py

When PostgreSQL is recovering files from archive it may not be accepting
connections so it's not possible to ask the recovery progress from PG
directly. Recovery progress in such cases is in practice the most recent
file of type "xlog" that pghoard has served. Expose this information in
the state file.

Report most recently served files in pghoard state

---

test/test_basebackup.py

recovery.signal file needs to be created for the backup restore to
complete.

tests: fix tablespace basebackup test for PG 12+

---

README.rst
pghoard/basebackup.py
pghoard/config.py
pghoard/restore.py
pghoard/rohmu/compressor.py
pghoard/rohmu/rohmufile.py
pghoard/rohmu/zstdfile.py

Taking basebackups of very large systems takes a long time. Previously
each basebackup chunk was compressed and encrypted completely
sequentially. (Uploading was done in parallel.) While GIL does not
allow fully utilizing a lot of CPU cores the native calls do release it
so this somewhat reduces basebackup duration on multi core nodes.
Test results with 44 GiB database, 23 basebackup chunks, zstd
compression:
```
Baseline:
CPU consumption: 100% - 120%
Operation duration: 510s
CPU time: 530s
One thread (but using ThreadPoolExecutor):
CPU consumption: 100% - 120%
Operation duration: 505s
CPU time: 533s
Two threads:
CPU consumption: 190% - 230%
Operation duration: 290s
CPU time: 586s
Five threads:
CPU consumption: 240% - 480%
Operation duration: 292s
CPU time: 970s
Two threads plus two zstd …
```

basebackup: Use multiple threads to compress and encrypt chunks

---

pghoard/rohmu/object_storage/google.py

We currently raise an exception if a HTTP-call fails, but we
exclude some cases.
Notably we exclude 500, 502, and 503 however we do not exclude 504
which this pull-request adds to the list.

Ignore HTTP 504 error codes

---

pghoard/rohmu/object_storage/google.py
requirements.txt
test/test_storage.py

Re-reading the same block of data or part of the block always failed.

rohmu: Fix re-reading data from GCS

---

pghoard/rohmu/object_storage/google.py
test/test_storage.py

getbytes length parameter was named incorrectly causing earlier
attempt to fix invalid implementation to actually cause regression.

rohmu: Fix GCS MediaStreamUpload

---

.pylintrc
Makefile
pghoard/postgres_command.py
pghoard/wal.py
requirements.txt
test/test_wal.py

When passing a file object to verify_wal, the header must always be read
from the beginning of the object.

pghoard: ensure that verify_wal read from the beginning of file objects

---

.style.yapf
.travis.yml
Makefile
requirements.dev.txt

Add the standard `yapf` formatting configuration and validation to the travis build with formatting configured to allow failures.

fmt: Add yapf formatting and travis build configuration

---

pghoard/config.py
pghoard/wal.py
test/conftest.py

Changes needed this time round were mostly around postgreql.conf
replacing keep_wal_segments with with keep_wal_size and the WAL
version header bump.

pg: add support for PostgreSQL 13

---

pghoard/rohmu/compressor.py

The CompressionStream in the rohmu/compressor.py is not used to do compression, its only use is in test cases.
The level param needs to be passed into the zstd_open instead, otherwise the default level of '0' is actually used.   
I double checked and a level of 0 is passed through to the zstandard package.   It results in slightly less compression than if level 3 was passed in.  **So pghoard zstd uses level 0 compression at the moment.**
My PR is a very small change to make sure the level is getting passed in, to make it possible to actually specify a compression level.

make sure that level gets used for zstd

---

pghoard/pghoard.py

This patch logs a warning if config has only basebackup_hour defined,
and not basebackup_minute.
It helps in debugging if someone missed it in documentation.

pghoard: log if backup_hour is ignore because backup_minute is None

---

Makefile
README.rst
pghoard/rohmu/object_storage/azure.py

azure-storage-python depends on deprecated packages in fedora33 and is no longer actively maintained
We are building this from our own fork of `python3-azure-sdk` to incorporate the changes mentioned by Rauli below. 
Changes can be found here: https://github.com/aiven/azure-sdk-for-python/tree/aiven/rpm_fixes

azure: Use azure-sdk instead of azure-storage-python

---

pghoard/rohmu/object_storage/azure.py

This should turn off the detailed logging of every http request and response.
```
Jan 14 11:10:45 foo-test-n1008 pghoard[12118]: azure.core.pipeline.policies.http_logging_policy Thread-6 INFO: Request method: 'PUT'
Jan 14 11:10:45 foo-test-n1008 pghoard[12118]: azure.core.pipeline.policies.http_logging_policy Thread-6 INFO: Request headers:
Jan 14 11:10:45 foo-test-n1008 pghoard[12118]: azure.core.pipeline.policies.http_logging_policy Thread-6 INFO:     'Content-Type': 'application/octet-stream'
Jan 14 11:10:45 foo-test-n1008 pghoard[12118]: azure.core.pipeline.policies.http_logging_policy Thread-6 INFO:     'Content-Length': '1133'
Jan 14 11:10:45 foo-test-n1008 pghoard[12118]: azure.core.pipeline.policies.http_logging_policy Thread-6 INFO:     'x-ms-version': 'REDACTED'
Jan 14 11:10:45 …
```

azure: Reduce logging verbocity of http_logging_policy

---

test/test_rohmu_dates.py

The unit test `test_parse_timestamp` currently fails for local timestamps whose timezone is in a western timezone, that is, local time has an offset negative from UTC like UTC-05:00.

test: fix parsing negative timezone offsets

---

README.rst
pghoard/rohmu/object_storage/google.py

Support operations over proxies. The support is implemented only
for the Google storage at this time. Proxy information is delivered
in the config, e.g.
{
"proxy_info": {
"type": "socks5",
"host": "proxy.example.com",
"port": 1080,
"user": "username",
"pass": "password"
}
}

rohmu/google: support connectivity through proxies

---

pghoard/restore.py

Context manager of multiprocess pool in fetcher does not seem to properly wait for the subprocesses to exit, let's join the pool manually (close need to be called before joining).
It looks like when pool gets destroyed, sometimes all the processes get SIGTERM (including the main process), which is not a desired behavior, we want to wait for the pool to finish its job and then quit properly.
It might potentially lead to an inconsistent state of restoration.

Properly handle fetcher pool when exiting

---

README.rst
pghoard/rohmu/object_storage/s3.py

Extend proxy support to s3 driver as well. Socks support requires botocore with https://github.com/boto/botocore/pull/2081 merged.

rohmu/s3: support connectivity through proxies

---

.gitignore
pghoard/compressor.py
pghoard/pghoard.py
test/test_compressor.py

On failed compression, the compressor thread would just jump to the next data in the queue after reporting an error.
Instead, make sure that a few retries are conducted on the same event just in case, and exit if it keeps failing.

handle exceptions in compressor threads

---

pghoard/rohmu/object_storage/swift.py

sample output result from listing an object:
{'bytes': 4245, 'last_modified': '2021-05-13T20:37:32.959340', 'hash': '5aa70b19655a26a7ec4edf926..', 'name': 'alxric/testfile.ini', 'content_type': 'application/octet-stream'}

swift: add hash to object result

---

pghoard/rohmu/object_storage/swift.py

This function has been puzzling me for a large part of the evening, so it's possible that I am missing something here, but as far as I read this, this function can never do anything useful in it's current state.
It will regardless of what happens always immediately delete the file again right after completing the download, leaving you with nothing.
But then again, original code has been there since 2016, so it's very likely me missing something here

swift: Do not delete succesfull file downloads

---

pghoard/rohmu/object_storage/swift.py

Previous fix was incorrect, this should make sure no temp files are leaked

swift: fix swift temp file deletion

---

pghoard/rohmu/object_storage/google.py
test/test_storage.py

When doing streaming upload, a `*` can be used for the total file size
in the `Content-Range` header of intermediate chunks. But the total
file size should be provided in the final chunk so that the uploading
can be finalized. Add a `peek` method into `MediaStreamUpload` so that
we can return the total file size when reading the fianl chunk.

rohmu/google: HttpError when streaming perfectly aligned file

---

.github/workflows/build.yml
README.rst
Vagrantfile
docs/development.rst
setup.py

Drop the support for python 3.7
Resolves: current broken pipeline issue.
rohmu is python 3.8 above
Python 3.7 is EOL, and pipeline for pghoard is broken because of python 3.7

Drop python 3.7 version since it's broken CI and EOL

---

pghoard/pghoard.py

for example: for alerting purpose
Emit a metric when there is unrecoverable error to quit main loop
So we can do some alert on services.
A metric will generate each time if there is a main loop quit.

Emit a metric when pghoard quits main loop

---

pghoard/basebackup/base.py
pghoard/basebackup/delta.py
pghoard/common.py
pghoard/transfer.py
test/basebackup/test_delta.py
test/test_common.py
test/test_transferagent.py

This PR improves the monitoring of pg basebackups. During a backup, it regularly checks how much data has been uploaded and compares this to the last recorded amount in a persisted progress file. If the upload is progressing, it updates the record with the new data and current time. If the backup has not advanced compared to the previous value, it reports the time elapsed since the last progress and emits stalled metrics. Once a backup is complete, the record is reset.
[SRE-7631]

Add progress based basebackup metrics

---

pghoard/fetcher.py

pghoard dispatches processes in charge of fetching files from sites. When starting such processes, pghoard provides  its config as an argument. Meaning that if pghoard gets restarted with a different config (e.g object storage got new credentials), the running file fetcher processes won't acknowledge this and will keep using the old config.
So, in order to change this behavior. Its better to provide the current config directly on each task instead of the process itself. This way the process can update the transfer to the object storage (in case the site's config changed).
Resolves: #BF-2385

refresh site creds on file fetcher processes

---

golang/pghoard_postgres_command_go.go
pghoard/common.py
pghoard/pghoard.py
pghoard/postgres_command.py
pghoard/webserver.py
test/test_pghoard.py
test/test_webserver.py

Changes:
* Added a new DownloadResultsProcessor thread, which validates downloaded files and saves them to the target: `pg_wal/<wal_name>.tmp -> pg_wal/<wal_name>.pghoard.prefetch`.
Files with "prefetch" suffix can be copied to the destination without extra checks now.
* Renaming prefetched WAL to target is carried out directly in the `pghoard_postgres_command_go`
* changed items type for "pending_download_ops" dict from "dict" to "dataclass" (PendingDownloadOp)
[BF-2247]
We observed that the startup process was only using 60 to 80% of a CPU. This means that we’re not supplying WAL files fast enough or that the restore_command takes too long to complete.
The idea would be to bypass the HTTP-call needed to check if we have a WAL file present from the `restore_command` to the pghoard main …

Pghoard restore_command optimization

---

pghoard/common.py
pghoard/pghoard.py
test/basebackup/test_basebackup.py
test/conftest.py
test/test_pghoard.py

Pghoard will try making backup in this cases, еven if the retries are over:
1. Backup was requested by operator (called related http endpoint)
2. More than `backup_interval` have passed since the last unsuccessful attempt
[BF-2390]
Pghoard can stuck in state, when it doesn't make backup after several failures. It just writes in log `Giving up backup after exceeding max retries` and only restart can help.

pghoard: ignore delta backup failures counter in some cases

---

pghoard/basebackup/base.py
pghoard/basebackup/delta.py
pghoard/transfer.py
test/test_common.py
test/test_transferagent.py

This PR refactors the basebackups monitoring introduced in PR #615. Previously, we reset the basebackup progress file whenever a new basebackup request was made, which resulted in not catching a few cases where pghoard restarts. Now, the progress file is only reset when a backup is successful, and we also record the total bytes uploaded in the file for the previous basebackup. If there is a retry due to a pghoard restart or a failed backup request, we check if progress has been made; if it has not exceeded the bytes uploaded in the previous state, we emit a stalled metric. Also, added logging for upload progress for each file and snapshot stages in a basebackup operation.
[SRE-7476]

refactor progress based basebackup metrics

---

pghoard/basebackup/delta.py
pghoard/transfer.py

Reduce the stalled logging for the snapshot process. Previously, we were not resetting last_flush_time, resulting in a lot of logs being printed if the previous base backup failed and the current progress surpassed the previous base backup progress for the snapshot process

fix: Reduce the stalled logging for snapshot

---

golang/pghoard_postgres_command_go.go
pghoard.spec
pghoard/config.py
pghoard/object_store.py
pghoard/postgres_command.py
pghoard/restore.py
pghoard/webserver.py
test/conftest.py
test/test_webserver.py

Support requesting authentication on the web server. This is intended to limit exposure from local redirects, open proxies and/or call out functionality.

webserver: support authentication on the webserver

---

pghoard/restore.py
test/test_restore.py

Current implementation use fixed retry (6) for base backup restore. However, on a large (2~4 TiB) database, there are more data to be transferred and will take longer. As a result, it is more likely to hit the limit.
This commit allows a dynamic number of retry, depends on the size of the base backup.
This seems to be the minimum change to avoid starting over base backup download when restoring a large database. I acknowledge that there are other and/or better ways to implement this.

Better retry for base backup restore

---

pghoard/restore.py

Commit 4869d8491cb6df9ced1613af1be5a3fd3dfbc358 added logic to make the number of retries dependent on the backup size. Instead of allowing for one error every 64GB allow for one every 10GB.
It's better to retry more than to start from scratch when things go wrong.

Add more retries when restoring a basebackup

---

pghoard/webserver.py

- do not prefetch timeline files
- adapt to PostgreSQL behaviour from the past 12 years and do not skip 0xFF WAL files.

Fix prefetch logic

---

pghoard/webserver.py
test/test_webserver.py

If PostgreSQL asks for a file, we need to copy it there not rename it if it already exists.
This is the case when PG asks for a timeline to be copied over to RECOVERYTIMELINE.

One more occurence of making pg_wal contents disappear

---

pghoard/pghoard.py
pghoard/receivexlog.py

Since we are only ever dumping it to a temp directory, use the --no-sync
argument.

Use --no-sync for pg_receivewal
